### ISSUE TITLE
Installation using brew not working

### ISSUE THREAD

**Issue by neeldhara** [AlexanderWillner/things.sh#11]
Installing via brew gives the following error:

`/usr/local/bin/things.sh: line 176: @: unbound variable`

**Comment by AlexanderWillner** [comment]
Could you run ```TRACE=1 /usr/local/bin/things.sh``` and provide the output? Which macOS version are you using? Also the output of ```bash -version``` please.

**Comment by neeldhara** [comment]
Thanks very much for taking a look! 

The output of the trace is [here](https://pastebin.com/raw/HJFuYHak).

I'm using macOS High Sierra (10.13.4). Also, `bash -version` gives:

`GNU bash, version 3.2.57(1)-release (x86_64-apple-darwin17)`

I used zsh for the installation, does that make a difference?

**Comment by AlexanderWillner** [comment]
Can you replace /usr/local/bin/things.sh with https://raw.githubusercontent.com/AlexanderWillner/things.sh/master/things.sh and see if this fixes your issue?

**Comment by neeldhara** [comment]
Why yes, it does! Thanks so much - much appreciated 🙂
