### ISSUE TITLE
ical integration

### ISSUE THREAD

**Issue by danielecook** [AlexanderWillner/things.sh#16]
Hello - 

Have you thought about outputing an ical file so it can be subscribed to? This would be useful for showing (and linking to) deadlines and schedules.

Happy to help with this - would be good if there was a way to output by 'area'.

Could be something like this:

```
things.sh ical --area "Work" > work.ical
```

If you run this as a cron job and output to a dropbox location, you can subscribe to the ical.

**Comment by AlexanderWillner** [comment]
Pushed a first draft.

**Comment by danielecook** [comment]
Wow this is awesome - I have been trying to find a way to do this for a long time.

1. Is there a way to filter by area?
1. I added a note on how to turn the due-dates into all-day events which I think makes more sense.
1. Is it possible to add the text description after the URL?

This is incredibly useful - thank you very much.

As far as using it - 

1. Create a cron job that outputs to dropbox

```
things.sh ical  >~/Dropbox/test.ical
```

2. Create a shared link and modify it by changing the `www` subdomain to `dl` and the dl param from 0 to 1

`https://www.dropbox.com/s/pl6jjdifcsjq65w/test.ical?dl=0`

Change to:

`https://dl.dropbox.com/s/pl6jjdifcsjq65w/test.ical?dl=1`

Then you can subscribe to it in ical and it should work. Ical is stupid in that it will not subscribe to a local file.

**Comment by AlexanderWillner** [comment]
Due dates: now all-day events, thanks.
Test description: added.
Filter: not implemented (yet), but possible/easy

**Comment by AlexanderWillner** [comment]
Please open another issue for further suggestions. Thanks for the feedback!
