### ISSUE TITLE
iCal Feed: Based on Start Dates + Projects / Area Reference

### ISSUE THREAD

**Issue by kennonb** [AlexanderWillner/things.sh#21]
Hi,

I haven't been here in a while, but I have to say the iCal feed is wonderful! 🎉 

I've done a quick hack to use Start Dates instead of Due Dates for my Calendar feed. This way I can see all my tasks for each day coming up. I also added some data to the feed to include the Project or Area next to the task name for reference.

I'd love to contribute and create options for this in the repo, but not sure how exactly to do that yet within the project structure you currently have.

Thanks!

**Comment by AlexanderWillner** [comment]
A bit late, but: Thanks for the nice words!
