### ISSUE TITLE
CSV export should default to UTF-8

### ISSUE THREAD

**Issue by jmsgwd** [AlexanderWillner/things.sh#27]
The documentation says that by default, CSV export generates a file "that is readable by Microsoft Excel in Europe, i.e., the default encoding is WINDOWS-1252 and the separator is ;".

I understand this is only a default, and it can be overridden using environment variables.

However, I suggest that the _default_ should be changed to UTF-8 and the more standard comma-separated values, for the following reasons:

- Current versions of Excel have no issues importing UTF-8 / comma-separated - you just have to use File > Import. When prompted for an encoding, select "Unicode (UTF-8)" from the list, and for Delimiters select "Comma". This works for me on Microsoft Excel for Mac Version 16
- Not everyone is using Microsoft Excel
- Not everyone is in Europe
- Not every Excel user in Europe is using Windows (especially not Things users!), hence WINDOWS-1252 is often not the default encoding anyway

The funny thing is, I am in Europe and I am using Excel. But the default encoding _still_ corrupts my data. Why? Because I use lots Unicode characters in my task notes like bullets, ticks, crosses, arrows, currency signs, emoji, foreign words, special characters, etc.

Remember Things is a Unicode app, and its SQLite database uses UTF-8.

The CSV export function should follow the principle of least surprise, and preserve users' Unicode notes data in its default setting. It should not corrupt or mangle their data by default.

**Comment by AlexanderWillner** [comment]
Thanks for the four feedback issues. Highly appreciated. However, can't promise I can work on them this year.

**Comment by jmsgwd** [comment]
Thanks for the response, I completely understand. I guess they'll go in your "Someday" list! ;-)
