### ISSUE TITLE
things.sh with Things 3 Beta

### ISSUE THREAD

**Issue by gerrymcil** [AlexanderWillner/things.sh#28]
Is it possible to tell things.sh where the Things database is? I'm using Things 3 **beta** so the location of the database differs slightly from the standard installation.

**Comment by AlexanderWillner** [comment]
Good point. Being a beta user myself, I just tested it: 
```shell
$ export THINGSDB=~/Library/Containers/com.culturedcode.ThingsMac.beta/Data/Library/Application\ Support/Cultured\ Code/Things/Things.sqlite3
$ things.sh inbox
```
