### ISSUE TITLE
Tasks with empty title are not exported

### ISSUE THREAD

**Issue by hummingwhale** [AlexanderWillner/things.sh#29]
Thank you for this awesome application. I have a couple of tasks which have notes but no titles. All except for one seem to be ignored when exporting the Things database via `things.sh csv > Things3Export.csv && open Things3Export.csv`. It would be great if the export would contain all tasks - regardless whether they have a title or not.

**Comment by hummingwhale** [comment]
@AlexanderWillner is it possible that the Group By clause in [this line](https://github.com/AlexanderWillner/things.sh/blob/01120256adc562ddcfc6d228d2b793c6b9ef9825/plugins/csv.sh#L42) produces the behavior I described above?

**Comment by AlexanderWillner** [comment]
Thanks. I can reproduce the issue, however, it's not caused by the identified line. Not sure currently what the issue is.

**Comment by AlexanderWillner** [comment]
btw: please note that I'm moving the features slowly to a [python based version of the script](https://github.com/AlexanderWillner/KanbanView). The issue seems not to apply to that version.

**Comment by hummingwhale** [comment]
Thank you for your feedback, @AlexanderWillner. I will check out the other repository.
