### ISSUE TITLE
 (Things v 3.17.4)  DB Location changed, Error in prepare

### ISSUE THREAD

**Issue by flegfleg** [AlexanderWillner/things.sh#36]
Hi, 
the new release of Things breaks the script in 2 ways: 

**1 DB location changed** 

Old: "`/Library/Group Containers/JLMPQHK86H.com.culturedcode.ThingsMac/Things Database.thingsdatabase/main.sqli`" 

New: "`/Library/Group Containers/JLMPQHK86H.com.culturedcode.ThingsMac/**ThingsData-XXXXX**/Things Database.thingsdatabase/main.sqli`"

**2 DB structure seemingly changed, i get the following error:** 

```
Error: in prepare, no such column:
TASK.dueDate
SELECT date(TASK.dueDate,"unixepoc..
```

**Comment by flegfleg** [comment]
Thanks for the quick answer! 
Maybe i am missing something, but i can not specify column names, i am using the `ical` option to write an ics file: 
`things.sh ical > deadlines.ical`

**Comment by mltucker** [comment]
These issues should be fixed in our fork. https://github.com/amazingmarvin/things.sh

**Comment by AlexanderWillner** [comment]
Thanks - just pushed the changes.
@mltucker I cherry-picked some changes and changed some missing parts. Your release changes look interesting...

**Comment by mltucker** [comment]
@AlexanderWillner cool, glad you could use some code. I would have made a PR but you’ve already ported to python so I didn’t want to bother you. The release thing is there so that non-technical users can just double click.

**Comment by AlexanderWillner** [comment]
Released.
