### ISSUE TITLE
schedule.sh broken with python3

### ISSUE THREAD

**Issue by mespeer** [AlexanderWillner/things.sh#39]
The schedule.sh plugin won't run with python3. I've changed my local copy to correct the issue.
current    
`title="$(python -c 'import urllib, sys; print urllib.quote(sys.argv[1])' "${array[3]}")"`
changed to
`title="$(python -c 'import urllib.parse, sys; print(urllib.parse.quote(sys.argv[1]))' "${array[3]}")"`

**Comment by AlexanderWillner** [comment]
Thanks! Fixed.
