### ISSUE TITLE
HowTo excel chart

### ISSUE THREAD

**Issue by dominik42** [AlexanderWillner/things.sh#6]
Hi Alexander,
thanks for your great work, exactly what I'm looking for in order to create a statistic for my GTD behavior. But how do you produce that example chart with the title "Things 3 Tasks (14 days)", the file in `img/example3.jpg` ? With `things.sh csh` I produce the csv file, import it into excel and create a pivot table from the column `creation date` but the result is different :-(
Can you please explain your steps in Excel (or Numbers).

Thanks in advance
Dominik

**Comment by dominik42** [comment]
Thanks for your fast response. 
Yesterday I've  copied only the things.sh as raw file. After your commits you mentioned, I've tried to install the recent version using homebrew but without success (I'm using macOS High Sierra 10.13.2)

```sh
Dominik@Doms-Mac:~\> brew install things.sh
==> Installing things.sh from alexanderwillner/tap
Error: The following formula:
  things.sh
cannot be installed as a binary package and must be built from source.
Install the Command Line Tools:
  xcode-select --install
```

Thereafter I've cloned this git repo and start directly from this directory.

```sh
Dominik@Doms-Mac:~/Documents/Dominik/things.sh\> ./things.sh -r '-14 days' statcsv
"Date";"Created";"Closed";"Cancelled";"Trashed"
2017-12-21;;;;
2017-12-22;;;;
2017-12-23;;;;
2017-12-24;;;;
2017-12-25;;;;
2017-12-26;;;;
2017-12-27;;;;
2017-12-28;;;;
2017-12-29;;;;
2017-12-30;;;;
2017-12-31;;;;
2018-01-01;;;;
2018-01-02;;;;
2018-01-03;;;;
2018-01-04;;;;
./things.sh: line 181: FUNCNAME[@]: unbound variable
./things.sh: line 165: 5: unbound variable
```
The errors mentioned in the last two lines but also the empty results for the 14 days are erroneous because it should exists created and modified entries for those days. The path to the DEFAULT_DB declared in `things.sh` is correct, the file exists and it's the same file Things 3 is using. ..
What made I wrong ?

**Comment by AlexanderWillner** [comment]
Thanks a lot. Interesting. I've to look into this (I'm also using 10.13.2).

**Comment by AlexanderWillner** [comment]
Please test release 2.1 (either via ```git pull``` or ```brew```)

**Comment by dominik42** [comment]
Hi,
with your last commit, it looks better. There are results from the DB. But the last line always contains those error message: 
```sh
Dominik@Doms-Mac:~/Documents/Dominik/things.sh\> ./things.sh -r '-14 days' statcsv
"Date";"Created";"Closed";"Cancelled";"Trashed"
2017-12-22;5;8;;1
2017-12-23;1;;;
2017-12-24;;1;;
2017-12-25;1;;;
2017-12-26;;;;
2017-12-27;;;;
2017-12-28;7;4;;
2017-12-29;5;3;;
2017-12-30;4;;;
2017-12-31;1;2;;
2018-01-01;6;;;
2018-01-02;5;8;;4
2018-01-03;10;11;;
2018-01-04;5;5;;
2018-01-05;1;2;;
./things.sh: line 182: FUNCNAME[@]: unbound variable
```

**Comment by AlexanderWillner** [comment]
Thank you. Please pull and test again.

**Comment by dominik42** [comment]
![](https://emojipedia-us.s3.amazonaws.com/thumbs/120/apple/118/thumbs-up-sign_1f44d.png)
