### ISSUE TITLE
Export appropriate date

### ISSUE THREAD

**Issue by groovytwo** [AlexanderWillner/things.sh#8]
Hello Alex & thank you! Your code works splendidly.

For items that are ordered by `<date>`, would it be possible to export the date as well?

For instance, with **'$ things.sh completed'** command, having the ability to export the **'creationDate'** and/or** 'Completion Date'** alongside would be great for logging completed tasks. 

Potentially many others find this information very useful. *Thanks* for considering Alex!

**Comment by groovytwo** [comment]
I am sorry, I got everything working, the problem was on my end. Thank you!

**Comment by biznachio** [comment]
@groovytwo,
Did you manage to add the Completion Date alongside the completed command output?

Can you share what you did?

I want to script the output, but all I see is the area, project, task.

Thanks for considering.
